CREATE TABLE CadastroEstudantes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  curso VARCHAR(255),
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL
);

CREATE TABLE Atividades (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome VARCHAR(100) NOT NULL,
  materia VARCHAR(50) NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  entrega VARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  estudanteId INTEGER REFERENCES CadastroEstudantes (id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Calendarios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  titulo VARCHAR(255) NOT NULL,
  descricao TEXT,
  data DATE NOT NULL,
  horario VARCHAR(255),
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL,
  estudanteId INTEGER REFERENCES CadastroEstudantes (id) ON DELETE SET NULL ON UPDATE CASCADE
);
