CREATE TABLE Atividades (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nome VARCHAR(100) NOT NULL,
  materia VARCHAR(50) NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  entrega VARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL,
  updatedAt DATETIME NOT NULL
);
